### PR TITLE
Adds initial working code.

### PR DESCRIPTION
**Pull request by caternuson**
Let the linting begin!

### CODE REVIEW

**Review by kattni — COMMENTED** [review]
Everything looks good. Does anyone from @adafruit/circuitpythonlibrarians have one of these to test?

**Comment by tannewt** [comment]
@kattni I don't either. Someone else can review anyway without testing it.

**Comment by ladyada** [comment]
@kattni dya wanna pick up one of these next time you order from 'fruit?
https://www.adafruit.com/product/992

**Comment by kattni** [comment]
Yep!

**Review by kattni — APPROVED** [review]
Looks good! Tested successfully on Feather M0. Thanks for doing this!

**Pull request merged**
